# Пользователи
## Создать нового пользователя

POST http://localhost:5000/users/register HTTP/1.1
Content-Type: application/json

{
  "userName": "Captain Jack",
  "email": "abracadabra5@mail.ru",
  "password": "shining",
  "userType": "pro"
}

###
## Авторизовать пользователя

POST http://localhost:5000/users/login HTTP/1.1
Content-Type: application/json

{
  "email": "abracadabra1@mail.ru",
  "password": "shining"
}

###

## Отправить изображение

PATCH http://localhost:5000/users/avatar HTTP/1.1
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJlbWFpbCI6ImFicmFjYWRhYnJhMUBtYWlsLnJ1IiwidXNlck5hbWUiOiJDYXB0YWluIEphY2siLCJpZCI6IjY3NzVhOGI3ZTIxOTNmOGUwZTM4YTZhZCIsImlhdCI6MTczNTc2NDE5NiwiZXhwIjoxNzM1OTM2OTk2fQ.ooSOKByEn__NGYZv0t2wsZXRKHu0s6tvI3UDvbkhkaw
Content-Type: multipart/form-data; boundary=----WebKitFormBoundary7MA4YWxkTrZu0gW

------WebKitFormBoundary7MA4YWxkTrZu0gW
Content-Disposition: form-data; name="avatar"; filename="screen.png"
Content-Type: image/png

< C:\Users\User\OneDrive\Рабочий стол\2438815-six-cities-3\upload\screen.png
------WebKitFormBoundary7MA4YWxkTrZu0gW--


###

## Проверить токен пользователя
GET http://localhost:5000/users/login HTTP/1.1
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJlbWFpbCI6ImFicmFjYWRhYnJhMUBtYWlsLnJ1IiwidXNlck5hbWUiOiJDYXB0YWluIEphY2siLCJpZCI6IjY3NzVhOGI3ZTIxOTNmOGUwZTM4YTZhZCIsImlhdCI6MTczNTc2NDE5NiwiZXhwIjoxNzM1OTM2OTk2fQ.ooSOKByEn__NGYZv0t2wsZXRKHu0s6tvI3UDvbkhkaw

###

## Добавить предложение в избранное
PATCH http://localhost:5000/users/favorites/6775e8a6106bdaa5e63b2abb HTTP/1.1
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJlbWFpbCI6ImFicmFjYWRhYnJhMUBtYWlsLnJ1IiwidXNlck5hbWUiOiJDYXB0YWluIEphY2siLCJpZCI6IjY3NzVhOGI3ZTIxOTNmOGUwZTM4YTZhZCIsImlhdCI6MTczNTc2NDE5NiwiZXhwIjoxNzM1OTM2OTk2fQ.ooSOKByEn__NGYZv0t2wsZXRKHu0s6tvI3UDvbkhkaw

###


## Удалить предложение из избранного
DELETE http://localhost:5000/users/favorites/6775e8a6106bdaa5e63b2abb HTTP/1.1
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJlbWFpbCI6ImFicmFjYWRhYnJhMUBtYWlsLnJ1IiwidXNlck5hbWUiOiJDYXB0YWluIEphY2siLCJpZCI6IjY3NzVhOGI3ZTIxOTNmOGUwZTM4YTZhZCIsImlhdCI6MTczNTc2NDE5NiwiZXhwIjoxNzM1OTM2OTk2fQ.ooSOKByEn__NGYZv0t2wsZXRKHu0s6tvI3UDvbkhkaw

###

## Получить список избранных предложений
GET http://localhost:5000/users/favorites HTTP/1.1
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJlbWFpbCI6ImFicmFjYWRhYnJhMUBtYWlsLnJ1IiwidXNlck5hbWUiOiJDYXB0YWluIEphY2siLCJpZCI6IjY3NzVhOGI3ZTIxOTNmOGUwZTM4YTZhZCIsImlhdCI6MTczNTc2NDE5NiwiZXhwIjoxNzM1OTM2OTk2fQ.ooSOKByEn__NGYZv0t2wsZXRKHu0s6tvI3UDvbkhkaw

###

